itj/itj/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from itj import settings
from mycatalog.sitemap import CompanySitemap, PositionSitemap, CategorySitemap, KeywordSitemap, StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'companies': CompanySitemap,
    'positions': PositionSitemap,
    'categories': CategorySitemap,
    'keywords': KeywordSitemap,
}

urlpatterns = [
    path('', include('mycatalog.urls'), name='mycatalog'),
    path(settings.ADMIN_URL, admin.site.urls),
    url(r'^', include('favicon.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='mycatalog/robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'mycatalog.views.error_404_view'

itj/mycatalog/urls.py
from django.urls import path

from . import views

app_name = 'mycatalog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('companies', views.CompanyListView.as_view(), name='companies'),
    path('keyword/<slug:slug>', views.IndexViewKeywordsFiltered.as_view(), name='index_keyword_filtered'),
    path('category/<slug:slug>', views.IndexViewCategoryFiltered.as_view(), name='index_category_filtered'),
    path('search', views.IndexViewSearchFiltered.as_view(), name='index_search_filtered'),
    path('remote-job/<int:pk>-<slug:slug>', views.PositionDetailView.as_view(), name='position_detail'),
    path('company/<slug:slug>', views.CompanyDetailView.as_view(), name='company_detail'),
    path('apply/<int:pk>', views.ExternalCounterURLRedirectView.as_view(), name='position-counter-redirect'),
]

itj/mycatalog/models.py
from django.db import models
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.contrib.staticfiles.storage import staticfiles_storage

from ckeditor.fields import RichTextField

URL_MAINSITE = 'MAIN'
URL_LINKEDIN = 'LINKEDIN'
URL_ANGELCO = 'ANGELCO'
URL_CRUNCHBASE = 'CRUNCHBASE'
URL_FACEBOOK = 'FACEBOOK'
URL_TWITTER = 'TWITTER'
URL_GLASSDOOR = 'GLASSDOOR'
URL_YOUTUBE = 'YOUTUBE'
URL_INSTAGRAM = 'INSTAGRAM'
URL_STACKOVERFLOW = 'STACKOVERFLOW'
URL_GITHUB = 'GITHUB'
URL_OTHER = 'OTHER'

URL_TYPES = (
    (URL_MAINSITE, 'Company Website'),
    (URL_LINKEDIN, 'LinkedIn'),
    (URL_ANGELCO, 'AngelList'),
    (URL_CRUNCHBASE, 'Crunchbase'),
    (URL_FACEBOOK, 'Facebook'),
    (URL_TWITTER, 'Twitter'),
    (URL_GLASSDOOR, 'Glassdoor'),
    (URL_YOUTUBE, 'YouTube'),
    (URL_INSTAGRAM, 'Instagram'),
    (URL_STACKOVERFLOW, 'Stackoverflow'),
    (URL_GITHUB, 'GitHub'),
    (URL_OTHER, 'OTHER'),
)


class CompanyDomainsClassifier(models.Model):
    class Meta:
        verbose_name = 'Company Domain'
        verbose_name_plural = 'Company Domains'

    domain_name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(blank=True, max_length=255, unique=True)

    def __str__(self):
        return self.domain_name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.domain_name)
        super(CompanyDomainsClassifier, self).save(*args, **kwargs)


class Company(models.Model):
    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    NUM_PEOPLE_TEN = 'TEN'
    NUM_PEOPLE_FIFTY = 'FIFTY'
    NUM_PEOPLE_HUNDRED = 'HUNDRED'
    NUM_PEOPLE_TWO_HUNDREDS = 'TWOHUNDREDS'
    NUM_PEOPLE_FIVE_HUNDREDS = 'FIVEHUNDREDS'
    NUM_PEOPLE_THOUSAND = 'THOUSAND'
    NUM_PEOPLE_LARGE = 'LARGE'

    NUM_PEOPLE = (
        (NUM_PEOPLE_TEN, '1-10'),
        (NUM_PEOPLE_FIFTY, '11-50'),
        (NUM_PEOPLE_HUNDRED, '51-100'),
        (NUM_PEOPLE_HUNDRED, '101-500'),
        (NUM_PEOPLE_THOUSAND, '501-1000'),
        (NUM_PEOPLE_LARGE, '>1000'),
    )

    company_name = models.CharField(max_length=250, unique=True)
    company_logo = models.ImageField(max_length=2000, null=True, blank=True, upload_to='logos')
    company_email = models.EmailField(max_length=250, null=True, blank=True)  # used for invoicing
    company_pitch = RichTextField(blank=True)
    description = RichTextField(blank=True)
    offices_locations = models.CharField(max_length=250, null=True, blank=True)
    enabled_flag = models.BooleanField(default=False, verbose_name='Published')
    pub_date = models.DateTimeField(verbose_name='Date created', auto_now_add=True)
    slug = models.SlugField(blank=True, max_length=255, unique=True)
    positions_url = models.URLField(blank=True)
    number_of_people = models.CharField(max_length=20, choices=NUM_PEOPLE, blank=True)
    edited_date = models.DateTimeField(verbose_name='Date edited', auto_now=True)
    funding = models.BooleanField(default=False)
    raised = models.CharField(max_length=50, blank=True)
    num_of_rounds = models.IntegerField(null=True, blank=True)
    last_round_announced_date = models.DateField(blank=True, null=True)
    domain_name = models.ManyToManyField(CompanyDomainsClassifier, blank=True)
    parced_source_id = models.CharField(max_length=100, blank=True)  # link to the parced company id
    founded_year = models.IntegerField(null=True, blank=True)
    other_info = RichTextField(blank=True)

    def __str__(self):
        return self.company_name

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.company_name)
        super(Company, self).save(*args, **kwargs)

    def company_logo_tag(self):
        if self.company_logo:
            logo = mark_safe('<img src="%s" width="40" alt="%s logo"/>' % (self.company_logo.url, self.company_name))
        else:
            logo = mark_safe('<img src="' + staticfiles_storage.url('mycatalog/nologo.png') + '" width="40" />')
        return logo

    company_logo_tag.short_description = 'Logo'

    @property
    def sorted_positions_set(self):
        return self.position_set.filter(enabled_flag=True, archive_flag=False).order_by('pub_date')

    @property
    def get_number_of_people_value(self):
        return self.get_number_of_people_display()

    @property
    def get_crunchbase_object(self):
        return self.companyurl_set.get(url_type=URL_CRUNCHBASE)

    @property
    def get_website_object(self):
        return self.companyurl_set.get(url_type=URL_MAINSITE)

    def get_absolute_url(self):
        return reverse('mycatalog:company_detail', args=[self.slug])


class CompanyUrl(models.Model):
    url_text = models.URLField(blank=False, null=False, max_length=500)
    url_type = models.CharField(max_length=50, choices=URL_TYPES, default=URL_OTHER, blank=False)
    company_name_ref = models.ForeignKey(Company, null=False, on_delete=models.CASCADE, blank=False)

    @property
    def get_url_type_value(self):
        return self.get_url_type_display()


class CompanyPositionParsingRule(models.Model):
    PARSING_RULE_USE_SELENIUM = 'USE_SELENIUM'
    PARSING_RULE_POSITIONS_LIST = 'POSITIONS_LIST'
    PARSING_RULE_POSITIONS_LIST_IFRAME = 'POSITIONS_LIST_IFRAME'
    PARSING_RULE_POSITIONS_LIST_EXCLUDE = 'POSITIONS_LIST_EXCLUDE'
    PARSING_RULE_POSITIONS_LIST_URL_PREFIX = 'POSITIONS_LIST_URL_PREFIX'
    PARSING_RULE_POSITION_IFRAME = 'POSITION_IFRAME'
    PARSING_RULE_POSITION_NAME = 'POSITION_NAME'
    PARSING_RULE_POSITION_LOCATION = 'POSITION_LOCATION'
    PARSING_RULE_POSITION_DESCRIPTION = 'POSITION_DESCRIPTION'
    PARSING_RULE_POSITION_DESCRIPTION_EXCLUDE = 'POSITION_DESCRIPTION_EXCLUDE'

    PARSING_RULES = (
        (PARSING_RULE_USE_SELENIUM, 'Use selenuim for parsing'),
        (PARSING_RULE_POSITIONS_LIST, 'Positions list'),
        (PARSING_RULE_POSITIONS_LIST_IFRAME, 'Positions list inside IFRAME'),
        (PARSING_RULE_POSITIONS_LIST_EXCLUDE, 'Positions list exclude'),
        (PARSING_RULE_POSITIONS_LIST_URL_PREFIX, 'Positions list URL prefix'),
        (PARSING_RULE_POSITION_IFRAME, 'Position IFRAME path'),
        (PARSING_RULE_POSITION_NAME, 'Title'),
        (PARSING_RULE_POSITION_LOCATION, 'Location'),
        (PARSING_RULE_POSITION_DESCRIPTION, 'Description'),
        (PARSING_RULE_POSITION_DESCRIPTION_EXCLUDE, 'Description exclude'),
    )

    parsing_rule = models.CharField(max_length=100, choices=PARSING_RULES, blank=False)
    parsing_path = models.CharField(max_length=1024, blank=False)
    company_name_ref = models.ForeignKey(Company, null=False, on_delete=models.CASCADE, blank=False)

    def __str__(self):
        return self.parsing_rule


class CompanyPositionUrlIgnore(models.Model):
    position_url = models.URLField(blank=False)
    position_name = models.CharField(max_length=250, blank=True, null=True)
    company_name_ref = models.ForeignKey(Company, null=False, on_delete=models.CASCADE, blank=False)
    creation_date = models.DateTimeField(verbose_name='Date created', auto_now_add=True)

    def __str__(self):
        return self.position_url


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    category_name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(blank=True, max_length=255, unique=True)

    def __str__(self):
        return self.category_name

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('mycatalog:index_category_filtered', args=[self.slug])


class CategoryKeyword(models.Model):  # keywords to assign category automatically during positions parsing
    keyword = models.CharField(max_length=100, unique=True)
    category_name_ref = models.ForeignKey(Category, null=False, on_delete=models.CASCADE, blank=False,
                                          verbose_name='Category')


class Keyword(models.Model):  # keywords to search positions
    keyword = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(blank=True, max_length=255, unique=True)
    parced_source_id = models.CharField(max_length=100, blank=True)  # link to the parced tag id

    def __str__(self):
        return self.keyword

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.keyword)
        super(Keyword, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('mycatalog:index_keyword_filtered', args=[self.slug])


class KeywordSynonym(models.Model):
    synonym = models.CharField(max_length=100, unique=True)
    keyword_ref = models.ForeignKey(Keyword, null=False, on_delete=models.CASCADE, blank=False, verbose_name='Keyword')

    def __str__(self):
        return self.synonym


class Position(models.Model):
    SALARY_CURRENCY_USD = 'USD'
    SALARY_CURRENCY_EUR = 'EUR'
    SALARY_CURRENCY_GBP = 'GBP'

    SALARY_CURRENCIES = (
        (SALARY_CURRENCY_USD, 'USD'),
        (SALARY_CURRENCY_EUR, 'EUR'),
        (SALARY_CURRENCY_GBP, 'GBP'),
    )

    SALARY_FREQUENCY_HOUR = 'HOUR'
    SALARY_FREQUENCY_MONTH = 'MONTH'
    SALARY_FREQUENCY_YEAR = 'YEAR'

    SALARY_FREQUENCIES = (
        (SALARY_FREQUENCY_HOUR, 'per hour'),
        (SALARY_FREQUENCY_MONTH, 'per month'),

itj/mycatalog/forms.py
from django import forms


class ParsingPositionsForm(forms.Form):
    hidden_positions_dict = forms.CharField(widget=forms.HiddenInput(), label='hidden_positions_dict')
    db_positions_to_archive = forms.CharField(widget=forms.HiddenInput(), label='db_positions_to_archive')
    parsing_rules_dict = forms.CharField(widget=forms.HiddenInput(), label='parsing_rules_dict')

itj/mycatalog/templates/mycatalog/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Google Tag Manager -->
    <script>{% if not debug %}(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TBH23TD');{% endif %}</script>
    <!-- End Google Tag Manager -->

    <meta charset="UTF-8">
    <meta http-equiv="Content-Language" content="en-us">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google" value="notranslate">
    <title>{% block title %}Remote jobs: development, testing, design and more | IT Careers{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}IT Careers helps you to find remote IT jobs worldwide. Software development, testing, design, management, marketing and many other different jobs available to you at one click.{% endblock %}">
    <meta name="keywords" content="Software Engineer,Product Manager,Project Manager,QA Engineer, DevOps, IT Jobs, Remote work, Remote jobs, Design jobs">
    <meta name="robots" content="{% block meta_indexfollow %}index,follow{% endblock %}" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="cleartype" content="on">
    <meta name="HandheldFriendly" content="true">

    <meta property="og:title" content="Remote jobs: development, testing, design and more | IT Careers"/>
    <meta property="og:description" content="IT Careers helps you to find remote IT jobs worldwide. Software development, testing, design, management, marketing and many other different jobs available to you at one click."/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="IT Careers">


    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'mycatalog/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'mycatalog/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'mycatalog/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'mycatalog/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'mycatalog/safari-pinned-tab.svg' %}" color="#000000">
    <meta name="msapplication-config" content="{% static 'mycatalog/browserconfig.xml' %}" />
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="theme-color" content="#ffffff">

    <meta http-equiv="Last-Modified" content="{% block last-modified %}{% now "D, d M Y H:i:s" %}{% endblock %} GMT">


    <!--
        <meta property="og:image" content="#">
        <meta property="og:url" content= "#"/>
    -->


<!--
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:description" content=""/>
    <meta name="twitter:creator" content=""/>
    <meta name="twitter:image:src" content=""/>
    <meta name="twitter:domain" content=""/>
    <meta name="twitter:site" content=""/>
    <meta name="twitter:url" content="">
    <link rel="image_src" href="">
-->

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>

    {% block extrahead %}{% endblock %}

    {% block js %}
        <script type="text/javascript">
            $(document).ready(function () {
                $('nav a').parents('li,ul').removeClass('active');
                $('a[href="' + this.location.pathname + '"]').parents('li,ul').addClass('active');
            })
        </script>
    <link rel="stylesheet" href="../../static/mycatalog/style.css">
    {% endblock %}
</head>
<body {% block extrabody %}{% endblock %}>
<!-- Google Tag Manager (noscript) -->
{% if not debug %}<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TBH23TD"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>{% endif %}
<!-- End Google Tag Manager (noscript) -->

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand py-0" href="{% url 'mycatalog:index' %}">
            <img src="{% static 'mycatalog/logo.png' %}"  height="40" alt="">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav mr-auto">
                {% if categories_list %}
                    {% for category in categories_list %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mycatalog:index_category_filtered' category.slug %}"><span class="sr-only">(current)</span><small>{{ category.category_name }}</small></a>
                        </li>
                    {% endfor %}
                {% endif %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'mycatalog:companies'%}"><span class="sr-only">(current)</span><small>Companies</small></a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0" action="{% url 'mycatalog:index_search_filtered' %}" method="get">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" value="{{ request.GET.search_string }}" name="search_string">
                <!--<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>-->
            </form>




        </div>
    </nav>
</header>

{% block content %}{% endblock %}

<!-- Footer start -->
{% include "mycatalog/footer.html" %}
<!-- Footer end -->

<!--Start of Tawk.to Script-->
<script type="text/javascript">
    {% if not debug %}
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/5cc2d934ee912b07bec4f873/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
    })();
    {% endif %}
</script>
<!--End of Tawk.to Script-->

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'mycatalog/style.css' %}">


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

itj/mycatalog/templates/mycatalog/company_detail.html
{% extends "mycatalog/base.html" %}

{% block last-modified %}{{company.edited_date|date:"D, d M Y H:i:s"}}{% endblock %}
{% block title %}Remote jobs at {{ company.company_name }} | IT Careers{% endblock %}
{% block meta_description %}{{ company.company_name }} is a remote friendly company. Enforce your career with the company being great IT professional. You could work remotely here.{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex flex-column pr-5">

                    <div class="d-flex flex-row">
                        {% if company.company_logo %}
                            <div class="pt-2 pr-3">
                                <img src="{{ company.company_logo.url }}"
                                     width="60px" alt="{{ company.company_name }} logo"/>
                            </div>
                        {% endif %}
                        <div class="pt-2 flex-column">
                            <h1><strong>{{ company.company_name }}</strong></h1>

                            {% if company.domain_name.all %}
                                <div class="h6">
                                    {% for domain in company.domain_name.all %}
                                        {% if not forloop.first %}/&nbsp{% endif %}{{ domain.domain_name }}
                                    {% endfor %}
                                </div>
                            {% endif %}

                            {% if company.funding and company.get_crunchbase_object.url_text %}
                                <div class="h6">
                                    <a class="text-dark" target="_blank" href="{{ company.get_crunchbase_object.url_text }}">
                                        Raised {{ company.raised }} in {{ company.num_of_rounds }}
                                        round{{ company.num_of_rounds|pluralize:",s" }}. The latest round was
                                        in {{ company.last_round_announced_date|date:"F Y" }}.
                                    </a>
                                </div>
                            {% endif %}

                            <div class="h6">
                                <ul class="list-inline">

                                    <li class="list-inline-item">
                                        {% if company.founded_year %}Founded in {{ company.founded_year }}.{% endif %}
                                    </li>
                                    <li class="list-inline-item">
                                        {% if company.number_of_people %}{{ company.get_number_of_people_value }} people.{% endif %}
                                    </li>
                                    <li class="list-inline-item">
                                        {% if company.offices_locations %}{{ company.offices_locations }}.{% endif %}
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    {% if company.get_website_object.url_text %}
                        <div class="d-flex flex-row ">
                            <div class="pb-2">
                                <a href="{{ company.get_website_object.url_text }}" target="_blank"
                                   class="text-info">Company website</a>
                            </div>
                        </div>
                    {% endif %}
                    <div class="d-flex flex-row ">
                        {% if company.companyurl_set.all %}
                            <ul class="list-inline">{% for comp_url in company.companyurl_set.all %}
                                {% if comp_url.url_type != 'MAIN' %}
                                    <li class="list-inline-item">
                                        <a href="{{ comp_url.url_text }}" target="_blank"
                                           class="text-info">{{ comp_url.get_url_type_value }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}</ul>
                        {% endif %}
                    </div>

                </div>
            </div>
            {% if company.company_pitch %}
                <div class="col-12 pt-4">
                    <div class="d-flex flex-column">
                        <div>{{ company.company_pitch|safe }}</div>
                    </div>
                </div>
            {% endif %}

            {% if company.description %}
                <div class="col-12 pt-4">
                    <div class="d-flex flex-column">
                        <div>{{ company.description|safe }}</div>
                    </div>
                </div>
            {% endif %}

            {% if company.companybenefit_set.all %}
                <div class="col-12">
                    <div class="d-flex flex-column">
                        <div class="h4">Benefits & Perks</div>
                        <div>
                            <ul>
                                {% for benefit in company.companybenefit_set.all %}
                                    <li>{{ benefit.benefit_name }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="col-12">
                <div class="d-flex flex-column py-3">
                    <div class="h6 text-secondary">Info last updated in {{ company.edited_date|date:"F Y" }}</div>
                </div>
            </div>

            <div class="col-12">
                <div class="d-flex flex-column">
                    <div class="h4 ">Job Openings</div>
                    <div>
                        {% if company.sorted_positions_set.all %}
                            {% for position in company.sorted_positions_set.all %}
                                <div class="row mb-1 border rounded my-2 py-1">
                                    <div class="col-sm">
                                        <div class="d-flex flex-column">
                                            <div class="px-2">
                                                <strong><a
                                                        href="{% url 'mycatalog:position_detail' position.id position.slug %}"
                                                        class="text-info">{{ position.position_name }}</a></strong>
                                            </div>
                                        </div>
                                    </div>
                                    {% include "mycatalog/positions_list_position_details.html" %}
                                </div>
                            {% endfor %}
                        {% else %}
                            <p>No active jobs so far.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

itj/mycatalog/templates/mycatalog/footer.html
{% load i18n %}

<!-- <footer class="footer">
    <div class="container">
        <span class="text-muted"></span>
    </div>
</footer>-->

itj/mycatalog/templates/mycatalog/header.html
{% load i18n %}

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'mycatalog:index' %}">ITCareers.dev</a>
        <!--
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">fff</span>
        </button>
        -->
        <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav mr-auto">
                <!--
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                -->
                {% block extraheader %}{% endblock %}
            </ul>

            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>